#!/usr/bin/env bash


yes | sudo pacman -Sc 
yes | sudo pacman -Scc 

yes | yay -Sc 
yes | yay -Scc 

rm -rf $HOME/.cache/ 
sudo sh -c "echo 1 >  /proc/sys/vm/drop_caches" 
sudo sh -c "echo 2 >  /proc/sys/vm/drop_caches" 
sudo sh -c "echo 3 >  /proc/sys/vm/drop_caches" 

sudo swapoff -a 
sudo swapon -a 

sudo pacman -Rns $(pacman -Qtdq) 

#source :- https://www.geeksforgeeks.org/how-to-clear-ram-memory-cache-buffer-and-swap-space-on-linux/
