#!/bin/bash

# ^c$var^ = fg color
# ^b$var^ = bg color
# ^d^ =  clear color

# kill -$(expr 34 + 1) $(pidof dwmblocks)   ### faster
# pkill -RTMIN+1 dwmblocks # slower
# kill -10 $(pidof dwmblocks)   or   pkill -SIGUSR1 dwmblocks ## refresh all block

color=#CC5500;

case $BLOCK_BUTTON in
    1) amixer -q set Capture toggle;;
    2) ;;
    3) subl ${0};;
    4) ;;
    5) ;;
esac



#### show mic usage icon on statusbar
DEFAULT_SOURCE=$(pactl info | awk '/Default Source/ { print $3 }')
SOURCE_MUTE=$(pactl get-source-mute "$DEFAULT_SOURCE" | awk '/^Mute/ { print $2 }')
MIC=""

if [ "$SOURCE_MUTE" = "yes" ]; then
    MIC=""
else
    MIC=" "
fi

printf " ^c$color^$MIC"

