#!/bin/bash

# ^c$var^ = fg color
# ^b$var^ = bg color
# ^d^ =  clear color

# kill -$(expr 34 + 1) $(pidof dwmblocks)   ### faster
# pkill -RTMIN+1 dwmblocks # slower
# kill -10 $(pidof dwmblocks)   or   pkill -SIGUSR1 dwmblocks ## refresh all block

color=#61afef;

case $BLOCK_BUTTON in
    1) ;;
    2) ;;
    3) subl ${0};;
    4) ;;
    5) ;;
esac


# usedMemory = MemTotal - MemAvailable ( currentlly used by 'free' and 'top' command) form #/proc/meminfo
# printf "  ^c$color^ $(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)"

# usedMemory = MemTotal - MemFree - Buffers - Cached - SReclaimable ( previously used by 'free' and 'top' command) form #/proc/meminfo
printf "  ^c$color^ $(printf "$(($(awk '/^(MemTotal|MemFree|Buffers|Cached|SReclaimable)/ { printf "%s-", $2 } END { printf "\n" }' /proc/meminfo | sed 's/-$//')))" | awk '{if ($1<1024*1024) printf "%.fM\n", $1/1024; else printf "%.1fG\n", $1/1024/1024}')"
