#!/bin/bash

# ^c$var^ = fg color
# ^b$var^ = bg color
# ^d^ =  clear color

# kill -$(expr 34 + 1) $(pidof dwmblocks)   ### faster
# pkill -RTMIN+1 dwmblocks # slower
# kill -10 $(pidof dwmblocks)   or   pkill -SIGUSR1 dwmblocks ## refresh all block


color1=#61afef;
color2=#61afef;


case $BLOCK_BUTTON in
    1) ;;
    2) ;;
    3) subl ${0};;
    4) ;;
    5) ;;
esac



disk=$(lsblk -ndo pkname $(findmnt -nvo SOURCE /))  # sda
file=/tmp/diskio
read -r sectorSize < /sys/block/$disk/queue/hw_sector_size
set -- $(awk '{print $3,$7}' /sys/block/$disk/stat)  ## means : set -- $1 $2

if [ -f "$file" ]; then read a b < "$file"; else a=$1; b=$2; fi
printf "%s %s" "$1" "$2" > "$file"

read=$(( ( $1 - a ) * sectorSize ))
write=$(( ( $2 - b ) * sectorSize ))

hr() { numfmt --to=si  "$1"; }
printf "^c$color1^%5sB^d^ ^c$color2^%4sB^d^\\n" "$(hr "$read")" "$(hr "$write")"


