#!/bin/bash

# ^c$var^ = fg color
# ^b$var^ = bg color
# ^d^ =  clear color

# kill -$(expr 34 + 1) $(pidof dwmblocks)   ### faster
# pkill -RTMIN+1 dwmblocks # slower
# kill -10 $(pidof dwmblocks)   or   pkill -SIGUSR1 dwmblocks ## refresh all block

color=#61afef;

case $BLOCK_BUTTON in
    1) ;;
    2) ;;
    3) subl ${0};;
    4) ;;
    5) ;;
esac



CAPACITY=$(cat /sys/class/power_supply/BAT*/capacity)
  STATUS=$(cat /sys/class/power_supply/BAT*/status)

  if [ $STATUS = "Charging" ]; then
    ICON=""
  else
    if [ $CAPACITY == 100 ]; then
      ICON=""
    else if [ $CAPACITY -lt 10 ]; then
      ICON=" warning"
    else
      ICON=$(printf "\u$(printf "%x" $((0xf578 + $CAPACITY / 10)))")
    fi fi
  fi


printf "  ^c$color^$ICON$CAPACITY%%"

